# Generated by Django 5.2.4 on 2026-05-06 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repartidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(help_text='Teléfono de contacto del repartidor.', max_length=20, verbose_name='Teléfono')),
                ('vehiculo', models.CharField(choices=[('BICICLETA', 'Bicicleta'), ('MOTO', 'Moto'), ('AUTO', 'Auto'), ('FURGON', 'Furgón'), ('A_PIE', 'A pie'), ('OTRO', 'Otro')], default='MOTO', help_text='Tipo de vehículo que usa para los repartos.', max_length=20, verbose_name='Vehículo')),
                ('foto', models.ImageField(blank=True, help_text='Foto del repartidor. Útil para que el cliente lo identifique.', null=True, upload_to='repartidores/', verbose_name='Foto')),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN_RUTA', 'En ruta'), ('INACTIVO', 'Inactivo')], default='INACTIVO', help_text='Estado actual del repartidor. El emprendedor ve este estado para decidir a quién asignar un pedido.', max_length=20, verbose_name='Estado')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('notas', models.TextField(blank=True, help_text='Notas internas del emprendedor sobre este repartidor.', null=True, verbose_name='Notas internas')),
            ],
            options={
                'verbose_name': 'Repartidor',
                'verbose_name_plural': 'Repartidores',
                'ordering': ['estado', 'user__first_name'],
            },
        ),
    ]
