# Generated by Django 5.2.4 on 2026-05-06 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repartidores', '0001_initial'),
        ('tiendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repartidor',
            name='tiendas',
            field=models.ManyToManyField(blank=True, help_text='Tiendas para las que trabaja este repartidor.', related_name='repartidores', to='tiendas.tienda', verbose_name='Tiendas'),
        ),
    ]
