# Generated by Django 5.2.4 on 2026-05-06 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repartidores', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='repartidor',
            name='user',
            field=models.OneToOneField(help_text='Cuenta de usuario del repartidor para acceder a la app.', on_delete=django.db.models.deletion.CASCADE, related_name='repartidor_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
