# Generated by Django 5.2.4 on 2026-05-06 21:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha del pedido')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('CONFIRMED', 'Confirmado'), ('PREPARING', 'Preparando'), ('ON_THE_WAY', 'En camino'), ('DELIVERED', 'Entregado'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Confirmado el')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Cerrado el')),
                ('tipo_entrega', models.CharField(choices=[('REPARTO', 'Despacho a domicilio'), ('RETIRO', 'Retiro en local')], default='REPARTO', help_text='Despacho a domicilio o retiro en el local.', max_length=10, verbose_name='Tipo de entrega')),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia bancaria'), ('LINK_PAGO', 'Link de pago')], default='EFECTIVO', help_text='Método de pago seleccionado por el cliente.', max_length=20, verbose_name='Método de pago')),
                ('subtotal_amount', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Subtotal')),
                ('delivery_cost', models.DecimalField(decimal_places=0, default=0, help_text='0 si es RETIRO en local o si el envío es gratuito según radio o cuadrante.', max_digits=10, verbose_name='Costo de envío')),
                ('total_amount', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Total')),
                ('customer_notes', models.TextField(blank=True, help_text="Instrucciones del cliente. Ej: 'Sin cebolla', 'Timbre roto, llamar al llegar'.", null=True, verbose_name='Notas del cliente')),
                ('tienda_notes', models.TextField(blank=True, help_text='Notas internas del emprendedor sobre este pedido. No las ve el cliente.', null=True, verbose_name='Notas internas')),
                ('loyverse_receipt_id', models.CharField(blank=True, help_text='ID del receipt creado en Loyverse para este pedido.', max_length=100, null=True, verbose_name='ID receipt Loyverse')),
                ('loyverse_synced', models.BooleanField(default=False, help_text='True cuando el pedido fue enviado exitosamente a Loyverse.', verbose_name='Sincronizado con Loyverse')),
                ('loyverse_synced_at', models.DateTimeField(blank=True, help_text='Fecha y hora en que se sincronizó con Loyverse.', null=True, verbose_name='Sincronizado el')),
                ('loyverse_sync_error', models.TextField(blank=True, help_text='Guarda el mensaje de error si la sincronización con Loyverse falló. Útil para debugging.', null=True, verbose_name='Error de sincronización')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('price_at_purchase', models.DecimalField(blank=True, decimal_places=0, help_text='Precio unitario al momento de realizar el pedido. Se guarda para que cambios futuros en el producto no afecten pedidos históricos.', max_digits=10, null=True, verbose_name='Precio al momento de la compra')),
                ('product_name_snapshot', models.CharField(blank=True, help_text='Nombre del producto al momento del pedido. Se preserva aunque el producto sea eliminado.', max_length=150, null=True, verbose_name='Nombre del producto')),
            ],
            options={
                'verbose_name': 'Ítem de Pedido',
                'verbose_name_plural': 'Ítems de Pedido',
            },
        ),
    ]
