# Generated by Django 5.2.4 on 2025-07-09 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
        ('usuarios', '0003_remove_direccion_direccion_direccion_block_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_latitude',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_longitude',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='billing_address',
            field=models.ForeignKey(blank=True, help_text='La dirección de facturación para este pedido (opcional).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders_as_billing_address', to='usuarios.direccion'),
        ),
        migrations.AddField(
            model_name='order',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='usuarios.cliente'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.ForeignKey(help_text='La dirección completa de envío para este pedido, referenciando el modelo Direccion.', on_delete=django.db.models.deletion.PROTECT, related_name='orders_as_delivery_address', to='usuarios.direccion'),
        ),
    ]
