# Generated by Django 5.2.4 on 2026-05-06 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0001_initial'),
        ('productos', '0002_initial'),
        ('tiendas', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_address',
            field=models.ForeignKey(blank=True, help_text='Opcional. Solo si la dirección de facturación es distinta a la de envío.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_as_billing_address', to='usuarios.direccion', verbose_name='Dirección de facturación'),
        ),
        migrations.AddField(
            model_name='order',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='usuarios.cliente', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.ForeignKey(blank=True, help_text='Dirección del cliente. Obligatoria para REPARTO y RETIRO (requerida para el ticket de Loyverse).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_as_delivery_address', to='usuarios.direccion', verbose_name='Dirección del cliente'),
        ),
        migrations.AddField(
            model_name='order',
            name='tienda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='tiendas.tienda', verbose_name='Tienda'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pedidos.order', verbose_name='Pedido'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.producto', verbose_name='Producto'),
        ),
    ]
