# Generated by Django 5.2.4 on 2026-05-09 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_initial'),
        ('repartidores', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='hora_entrega_est',
            field=models.DateTimeField(blank=True, help_text='Estimación de cuándo llegará el pedido al cliente.', null=True, verbose_name='Hora de entrega estimada'),
        ),
        migrations.AddField(
            model_name='order',
            name='modo_asignacion',
            field=models.CharField(choices=[('LIBRE', 'Libre — cualquier repartidor puede tomarlo'), ('CERRADO', 'Cerrado — asignado a un repartidor específico')], default='LIBRE', help_text='LIBRE: cualquier repartidor puede tomarlo. CERRADO: asignado a uno específico.', max_length=10, verbose_name='Modo de asignación'),
        ),
        migrations.AddField(
            model_name='order',
            name='repartidor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_asignados', to='repartidores.repartidor', verbose_name='Repartidor asignado'),
        ),
    ]
