# Generated by Django 5.2.4 on 2026-05-06 15:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_alter_orderitem_unique_together_and_more'),
        ('productos', '0003_alter_categoria_options_alter_producto_options_and_more'),
        ('tiendas', '0003_alter_radioenvio_options_tienda_acepta_efectivo_and_more'),
        ('usuarios', '0002_sellerprofile_whatsapp_alter_sellerprofile_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cerrado el'),
        ),
        migrations.AddField(
            model_name='order',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Confirmado el'),
        ),
        migrations.AddField(
            model_name='order',
            name='loyverse_receipt_id',
            field=models.CharField(blank=True, help_text='ID del receipt creado en Loyverse para este pedido.', max_length=100, null=True, verbose_name='ID receipt Loyverse'),
        ),
        migrations.AddField(
            model_name='order',
            name='loyverse_sync_error',
            field=models.TextField(blank=True, help_text='Guarda el mensaje de error si la sincronización con Loyverse falló. Útil para debugging.', null=True, verbose_name='Error de sincronización'),
        ),
        migrations.AddField(
            model_name='order',
            name='loyverse_synced',
            field=models.BooleanField(default=False, help_text='True cuando el pedido fue enviado exitosamente a Loyverse.', verbose_name='Sincronizado con Loyverse'),
        ),
        migrations.AddField(
            model_name='order',
            name='loyverse_synced_at',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que se sincronizó con Loyverse.', null=True, verbose_name='Sincronizado el'),
        ),
        migrations.AddField(
            model_name='order',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia bancaria'), ('LINK_PAGO', 'Link de pago')], default='EFECTIVO', help_text='Método de pago seleccionado por el cliente.', max_length=20, verbose_name='Método de pago'),
        ),
        migrations.AddField(
            model_name='order',
            name='tipo_entrega',
            field=models.CharField(choices=[('REPARTO', 'Despacho a domicilio'), ('RETIRO', 'Retiro en local')], default='REPARTO', help_text='Despacho a domicilio o retiro en el local.', max_length=10, verbose_name='Tipo de entrega'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_name_snapshot',
            field=models.CharField(blank=True, help_text='Nombre del producto al momento del pedido. Se preserva aunque el producto sea eliminado.', max_length=150, null=True, verbose_name='Nombre del producto'),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_address',
            field=models.ForeignKey(blank=True, help_text='Opcional. Solo si la dirección de facturación es distinta a la de envío.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_as_billing_address', to='usuarios.direccion', verbose_name='Dirección de facturación'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='usuarios.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_notes',
            field=models.TextField(blank=True, help_text="Instrucciones del cliente. Ej: 'Sin cebolla', 'Timbre roto, llamar al llegar'.", null=True, verbose_name='Notas del cliente'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.ForeignKey(blank=True, help_text='Dirección del cliente. Obligatoria para REPARTO y RETIRO (requerida para el ticket de Loyverse).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_as_delivery_address', to='usuarios.direccion', verbose_name='Dirección del cliente'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_cost',
            field=models.DecimalField(decimal_places=0, default=0, help_text='0 si es RETIRO en local o si el envío es gratuito según radio o cuadrante.', max_digits=10, verbose_name='Costo de envío'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha del pedido'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('CONFIRMED', 'Confirmado'), ('PREPARING', 'Preparando'), ('ON_THE_WAY', 'En camino'), ('DELIVERED', 'Entregado'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='order',
            name='subtotal_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tienda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='tiendas.tienda', verbose_name='Tienda'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tienda_notes',
            field=models.TextField(blank=True, help_text='Notas internas del emprendedor sobre este pedido. No las ve el cliente.', null=True, verbose_name='Notas internas'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pedidos.order', verbose_name='Pedido'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price_at_purchase',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Precio unitario al momento de realizar el pedido. Se guarda para que cambios futuros en el producto no afecten pedidos históricos.', max_digits=10, null=True, verbose_name='Precio al momento de la compra'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.producto', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Cantidad'),
        ),
    ]
