# Generated by Django 5.2.4 on 2026-05-06 21:22

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[('BUYER', 'Comprador'), ('SELLER', 'Vendedor/Comerciante')], default='BUYER', help_text='Define si el usuario es un comprador o un vendedor.', max_length=10, verbose_name='Tipo de Usuario')),
                ('groups', models.ManyToManyField(blank=True, help_text='Los grupos a los que pertenece este usuario. Un usuario obtendrá todos los permisos concedidos a cada uno de sus grupos.', related_name='custom_user_groups', related_query_name='custom_user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Permisos específicos para este usuario.', related_name='custom_user_permissions', related_query_name='custom_user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario Personalizado',
                'verbose_name_plural': 'Usuarios Personalizados',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BuyerProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='buyer_profile', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Asociado')),
            ],
            options={
                'verbose_name': 'Perfil de Comprador',
                'verbose_name_plural': 'Perfiles de Compradores',
            },
        ),
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='seller_profile', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Asociado')),
                ('telefono', models.CharField(blank=True, help_text='Teléfono de contacto general (opcional).', max_length=20, null=True, verbose_name='Teléfono de Contacto')),
                ('whatsapp', models.CharField(default='', help_text='Número de WhatsApp en formato internacional. Ej: +56912345678', max_length=15, verbose_name='WhatsApp')),
                ('rut', models.CharField(help_text='Rol Único Tributario de la empresa o persona natural.', max_length=12, unique=True, verbose_name='RUT / DNI')),
                ('razon_social', models.CharField(help_text='Nombre legal de la empresa o persona natural.', max_length=150, verbose_name='Razón Social')),
                ('giro', models.CharField(help_text='Actividad económica principal del vendedor.', max_length=150, verbose_name='Giro o actividad')),
                ('direccion_fiscal', models.CharField(help_text='Dirección registrada para fines tributarios.', max_length=255, verbose_name='Dirección Fiscal')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Perfil de Vendedor',
                'verbose_name_plural': 'Perfiles de Vendedores',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Apellido')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('is_guest', models.BooleanField(default=False, help_text='Indica si este cliente es un invitado (no tiene cuenta de usuario).')),
                ('guest_uuid', models.UUIDField(blank=True, default=uuid.uuid4, help_text='Identificador único para clientes invitados.', null=True, unique=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente_data', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Registrado')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta', models.CharField(blank=True, help_text='Ej: Casa, Oficina, Principal', max_length=50, null=True)),
                ('calle', models.CharField(help_text='Nombre de la calle o avenida.', max_length=255)),
                ('numero', models.CharField(help_text='Número de la dirección.', max_length=20)),
                ('tipo_propiedad', models.CharField(choices=[('Casa', 'Casa'), ('Edificio', 'Edificio'), ('Condominio', 'Condominio')], default='Casa', help_text='Selecciona el tipo de propiedad (Casa, Edificio, Condominio).', max_length=20)),
                ('departamento', models.CharField(blank=True, help_text='Número de departamento, oficina, etc.', max_length=20, null=True)),
                ('block', models.CharField(blank=True, help_text='Número o nombre del bloque/torre dentro del complejo (ej: Bloque A, Torre 3).', max_length=50, null=True)),
                ('nombre_condominio', models.CharField(blank=True, help_text='Nombre del condominio o complejo.', max_length=100, null=True)),
                ('comuna', models.CharField(help_text='Comuna o distrito.', max_length=100)),
                ('ciudad', models.CharField(help_text='Ciudad.', max_length=100)),
                ('region', models.CharField(help_text='Región o estado.', max_length=100)),
                ('codigo_postal', models.CharField(blank=True, help_text='Código postal.', max_length=10, null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, help_text='Latitud obtenida de la validación.', max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, help_text='Longitud obtenida de la validación.', max_digits=9, null=True)),
                ('validada', models.BooleanField(default=False, help_text='Indica si la dirección ha sido validada por una API de mapas.')),
                ('tipo_direccion', models.CharField(blank=True, help_text="Tipo de dirección (ej. 'Envío', 'Facturación').", max_length=50, null=True)),
                ('principal', models.BooleanField(default=False, help_text='Define si es la dirección principal para este cliente.')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to='usuarios.cliente', verbose_name='Cliente Asociado')),
            ],
            options={
                'verbose_name_plural': 'Direcciones',
                'ordering': ['-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('guest_uuid__isnull', True), ('user__isnull', False)), models.Q(('guest_uuid__isnull', False), ('user__isnull', True)), _connector='OR'), name='user_or_guest_uuid_not_both'),
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user',), name='unique_cliente_for_user'),
        ),
        migrations.AddConstraint(
            model_name='direccion',
            constraint=models.UniqueConstraint(condition=models.Q(('principal', True)), fields=('cliente',), name='unique_principal_address_per_client'),
        ),
    ]
