# Generated by Django 5.2.4 on 2026-05-07 03:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyerprofile',
            options={'verbose_name': 'Perfil de Cliente', 'verbose_name_plural': 'Perfiles de Clientes'},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterModelOptions(
            name='direccion',
            options={'ordering': ['-id'], 'verbose_name': 'Dirección', 'verbose_name_plural': 'Direcciones'},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_type',
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_cliente',
            field=models.BooleanField(default=True, help_text='Activo por defecto. El usuario puede comprar en las tiendas de la plataforma.', verbose_name='Es cliente'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_repartidor',
            field=models.BooleanField(default=False, help_text='Se activa cuando el usuario completa el registro como repartidor.', verbose_name='Es repartidor'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_vendedor',
            field=models.BooleanField(default=False, help_text='Se activa cuando el usuario completa el registro como emprendedor.', verbose_name='Es vendedor'),
        ),
        migrations.AlterField(
            model_name='buyerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='buyer_profile', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='is_guest',
            field=models.BooleanField(default=False, help_text='True si el cliente no tiene cuenta registrada.', verbose_name='Es invitado'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente_data', to=settings.AUTH_USER_MODEL, verbose_name='Usuario registrado'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(help_text='El email es único y se usa para iniciar sesión.', max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='custom_user_groups', related_query_name='custom_user', to='auth.group', verbose_name='Grupos'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='custom_user_permissions', related_query_name='custom_user', to='auth.permission', verbose_name='Permisos'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='block',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='calle',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='ciudad',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to='usuarios.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='comuna',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='departamento',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='etiqueta',
            field=models.CharField(blank=True, help_text='Ej: Casa, Oficina', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitud obtenida de Google Maps.', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitud obtenida de Google Maps.', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='nombre_condominio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='numero',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='principal',
            field=models.BooleanField(default=False, help_text='Dirección principal del cliente.'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='region',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='tipo_direccion',
            field=models.CharField(blank=True, help_text="Ej: 'Envío', 'Facturación'.", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='tipo_propiedad',
            field=models.CharField(choices=[('Casa', 'Casa'), ('Edificio', 'Edificio'), ('Condominio', 'Condominio')], default='Casa', max_length=20),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='validada',
            field=models.BooleanField(default=False, help_text='True si fue validada por Google Maps.'),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='giro',
            field=models.CharField(help_text='Actividad económica principal.', max_length=150, verbose_name='Giro o actividad'),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='rut',
            field=models.CharField(help_text='RUT de la empresa o persona natural. Ej: 12345678-9', max_length=12, unique=True, verbose_name='RUT'),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='seller_profile', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='whatsapp',
            field=models.CharField(default='', help_text='Formato internacional. Ej: +56912345678', max_length=15, verbose_name='WhatsApp'),
        ),
    ]
