# Generated by Django 5.2.4 on 2026-05-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='whatsapp',
            field=models.CharField(default='', help_text='Número de WhatsApp en formato internacional. Ej: +56912345678', max_length=15, verbose_name='WhatsApp'),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='telefono',
            field=models.CharField(blank=True, help_text='Teléfono de contacto general (opcional).', max_length=20, null=True, verbose_name='Teléfono de Contacto'),
        ),
    ]
