# Generated by Django 5.2.4 on 2025-07-09 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_cliente_email_cliente_is_guest_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direccion',
            name='direccion',
        ),
        migrations.AddField(
            model_name='direccion',
            name='block',
            field=models.CharField(blank=True, help_text='Número o nombre del bloque/torre dentro del complejo (ej: Bloque A, Torre 3).', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='direccion',
            name='calle',
            field=models.CharField(default='', help_text='Nombre de la calle o avenida.', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='direccion',
            name='ciudad',
            field=models.CharField(default='', help_text='Ciudad.', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='direccion',
            name='codigo_postal',
            field=models.CharField(blank=True, help_text='Código postal.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='direccion',
            name='comuna',
            field=models.CharField(default='', help_text='Comuna o distrito.', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='direccion',
            name='departamento',
            field=models.CharField(blank=True, help_text='Número de departamento, oficina, etc.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='direccion',
            name='nombre_condominio',
            field=models.CharField(blank=True, help_text='Nombre del condominio o complejo.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='direccion',
            name='numero',
            field=models.CharField(default='', help_text='Número de la dirección.', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='direccion',
            name='principal',
            field=models.BooleanField(default=False, help_text='Define si es la dirección principal para este cliente.'),
        ),
        migrations.AddField(
            model_name='direccion',
            name='region',
            field=models.CharField(default='', help_text='Región o estado.', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='direccion',
            name='tipo_direccion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='direccion',
            name='tipo_propiedad',
            field=models.CharField(choices=[('Casa', 'Casa'), ('Edificio', 'Edificio'), ('Condominio', 'Condominio')], default='Casa', help_text='Selecciona el tipo de propiedad (Casa, Edificio, Condominio).', max_length=20),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='etiqueta',
            field=models.CharField(blank=True, help_text='Ej: Casa, Oficina, Principal', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitud obtenida de la validación.', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitud obtenida de la validación.', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='validada',
            field=models.BooleanField(default=False, help_text='Indica si la dirección ha sido validada por una API de mapas.'),
        ),
    ]
