# Generated by Django 5.2.4 on 2026-05-13 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_buyerprofile_options_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='apellido_materno',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Apellido materno'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Apellido paterno'),
        ),
    ]
