# Generated by Django 5.2.4 on 2025-07-13 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_remove_direccion_direccion_direccion_block_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='guest_id',
            field=models.UUIDField(blank=True, help_text='Identificador único para clientes invitados.', null=True, unique=True),
        ),
    ]
