# Generated by Django 5.2.4 on 2025-07-17 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_cliente_guest_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='guest_id',
        ),
    ]
