# Generated by Django 5.2.4 on 2026-05-06 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_id', models.CharField(blank=True, help_text='Identificador único para clientes no registrados. Se gestiona desde el frontend.', max_length=255, null=True, unique=True, verbose_name='ID de invitado')),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia bancaria'), ('LINK_PAGO', 'Link de pago')], default='EFECTIVO', help_text='Método de pago seleccionado. Afecta el precio unitario de los items.', max_length=20, verbose_name='Método de pago')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Carrito',
                'verbose_name_plural': 'Carritos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ItemCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=0, help_text='Precio al momento de agregar al carrito según el método de pago seleccionado.', max_digits=10, verbose_name='Precio unitario')),
            ],
            options={
                'verbose_name': 'Ítem de Carrito',
                'verbose_name_plural': 'Ítems de Carrito',
                'ordering': ['id'],
            },
        ),
    ]
