# Generated by Django 5.2.4 on 2026-05-06 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carritos', '0001_initial'),
        ('tiendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='tienda',
            field=models.ForeignKey(blank=True, help_text='Tienda a la que pertenecen los productos del carrito.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carritos', to='tiendas.tienda', verbose_name='Tienda'),
        ),
    ]
