# Generated by Django 5.2.4 on 2026-05-06 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carritos', '0002_initial'),
        ('tiendas', '0003_alter_radioenvio_options_tienda_acepta_efectivo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia bancaria'), ('LINK_PAGO', 'Link de pago')], default='EFECTIVO', help_text='Método de pago seleccionado. Afecta el precio unitario de los items.', max_length=20, verbose_name='Método de pago'),
        ),
        migrations.AddField(
            model_name='carrito',
            name='tienda',
            field=models.ForeignKey(blank=True, help_text='Tienda a la que pertenecen los productos del carrito.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carritos', to='tiendas.tienda', verbose_name='Tienda'),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='guest_id',
            field=models.CharField(blank=True, help_text='Identificador único para clientes no registrados. Se gestiona desde el frontend.', max_length=255, null=True, unique=True, verbose_name='ID de invitado'),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carrito', to=settings.AUTH_USER_MODEL, verbose_name='Usuario registrado'),
        ),
        migrations.AlterField(
            model_name='itemcarrito',
            name='cantidad',
            field=models.PositiveIntegerField(default=1, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='itemcarrito',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=0, help_text='Precio al momento de agregar al carrito según el método de pago seleccionado.', max_digits=10, verbose_name='Precio unitario'),
        ),
    ]
