# Generated by Django 5.2.4 on 2026-05-08 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carritos', '0003_initial'),
        ('productos', '0002_initial'),
        ('tiendas', '0002_initial'),
        ('usuarios', '0002_alter_buyerprofile_options_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='metodo_pago',
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='tienda',
        ),
        migrations.AlterField(
            model_name='carrito',
            name='guest_id',
            field=models.CharField(blank=True, help_text='Identificador único para clientes no registrados.', max_length=255, null=True, unique=True, verbose_name='ID de invitado'),
        ),
        migrations.AlterField(
            model_name='itemcarrito',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=0, help_text='Precio al momento de agregar según el método de pago del grupo.', max_digits=10, verbose_name='Precio unitario'),
        ),
        migrations.CreateModel(
            name='GrupoCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_entrega', models.CharField(choices=[('REPARTO', 'Despacho a domicilio'), ('RETIRO', 'Retiro en local')], default='REPARTO', max_length=10, verbose_name='Tipo de entrega')),
                ('costo_envio', models.DecimalField(blank=True, decimal_places=0, help_text='Se calcula automáticamente según radio/cuadrante. 0 si es retiro o envío gratis.', max_digits=10, null=True, verbose_name='Costo de envío')),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia bancaria'), ('LINK_PAGO', 'Link de pago')], default='EFECTIVO', help_text='Cada tienda puede tener un método de pago diferente.', max_length=20, verbose_name='Método de pago')),
                ('hora_sugerida_cliente', models.TimeField(blank=True, help_text='Hora preferida de entrega o retiro sugerida por el cliente.', null=True, verbose_name='Hora sugerida por el cliente')),
                ('hora_confirmada', models.TimeField(blank=True, help_text='Hora confirmada por el emprendedor via WhatsApp. Puede diferir de la sugerida si el local tiene alta demanda.', null=True, verbose_name='Hora confirmada por el emprendedor')),
                ('notas_cliente', models.TextField(blank=True, help_text="Instrucciones específicas para esta tienda. Ej: 'Sin cebolla', 'Timbre roto'.", null=True, verbose_name='Notas del cliente')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='carritos.carrito', verbose_name='Carrito')),
                ('direccion_entrega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos_carrito', to='usuarios.direccion', verbose_name='Dirección de entrega')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_carrito', to='tiendas.tienda', verbose_name='Tienda')),
            ],
            options={
                'verbose_name': 'Grupo de Carrito',
                'verbose_name_plural': 'Grupos de Carrito',
                'ordering': ['tienda__nombre'],
                'unique_together': {('carrito', 'tienda')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='itemcarrito',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='itemcarrito',
            name='grupo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='carritos.grupocarrito', verbose_name='Grupo de carrito'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='itemcarrito',
            unique_together={('grupo', 'producto')},
        ),
        migrations.RemoveField(
            model_name='itemcarrito',
            name='carrito',
        ),
    ]
