# Generated by Django 5.2.4 on 2025-07-29 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('sku', models.CharField(blank=True, help_text='Identificador único del producto dentro de la tienda (ej. SKU_ALF_CHOC_001).', max_length=50, null=True)),
                ('codigo_barras_oficial', models.CharField(blank=True, help_text='Código de barras oficial (GTIN, EAN, UPC) del producto. Único a nivel global.', max_length=50, null=True, unique=True, verbose_name='Código de Barras GTIN/EAN/UPC')),
                ('imagen_qr_generado', models.ImageField(blank=True, help_text='Código QR generado automáticamente por la plataforma para gestión interna.', null=True, upload_to='codigos_qr/')),
                ('descripcion', models.TextField(blank=True, help_text='Aparece en la tarjeta y el modal de producto (máx. 300 caracteres).', verbose_name='Descripción corta')),
                ('precio_efectivo', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Precio (efectivo / transferencia)')),
                ('precio_tarjeta', models.DecimalField(decimal_places=0, help_text='Si no quieres recargo, pon el mismo valor que en efectivo.', max_digits=10, verbose_name='Precio (tarjeta débito‑crédito)')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('disponible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='SubCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name_plural': 'Subcategorías',
                'ordering': ['nombre'],
            },
        ),
    ]
