# Generated by Django 5.2.4 on 2025-07-04 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tiendas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='tiendas.tienda')),
            ],
            options={
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
                'unique_together': {('tienda', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='SubCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='productos.categoria')),
            ],
            options={
                'verbose_name_plural': 'Subcategorías',
                'ordering': ['nombre'],
                'unique_together': {('categoria', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, help_text='Aparece en la tarjeta y el modal de producto (máx. 300 caracteres).', verbose_name='Descripción corta')),
                ('precio_efectivo', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Precio (efectivo / transferencia)')),
                ('precio_tarjeta', models.DecimalField(decimal_places=0, help_text='Si no quieres recargo, pon el mismo valor que en efectivo.', max_digits=10, verbose_name='Precio (tarjeta débito‑crédito)')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('disponible', models.BooleanField(default=True)),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='tiendas.tienda')),
                ('subcategoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='productos.subcategoria')),
            ],
            options={
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
    ]
