# Generated by Django 5.2.4 on 2026-05-06 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('orden_display', models.PositiveIntegerField(default=0, help_text='Controla el orden en que aparece la categoría en la tienda. Menor número = primero.', verbose_name='Orden de visualización')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['orden_display', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, help_text='Aparece en la tarjeta y el modal de producto (máx. 300 caracteres).', verbose_name='Descripción corta')),
                ('sku', models.CharField(blank=True, help_text='Identificador único del producto dentro de la tienda. Ej: SKU_ALF_CHOC_001.', max_length=50, null=True, verbose_name='SKU')),
                ('codigo_barras_oficial', models.CharField(blank=True, help_text='Código de barras oficial del producto. Único a nivel global en la plataforma.', max_length=50, null=True, unique=True, verbose_name='Código de Barras GTIN/EAN/UPC')),
                ('precio_efectivo', models.DecimalField(decimal_places=0, help_text='Precio para pagos en efectivo o transferencia.', max_digits=10, verbose_name='Precio efectivo / transferencia')),
                ('precio_tarjeta', models.DecimalField(decimal_places=0, help_text='Precio con recargo por tarjeta. Si no hay recargo, ingresa el mismo valor que efectivo.', max_digits=10, verbose_name='Precio tarjeta débito/crédito')),
                ('stock', models.PositiveIntegerField(default=0, help_text='Cantidad disponible en inventario.', verbose_name='Stock')),
                ('disponible', models.BooleanField(default=True, help_text='Controla si el producto se muestra en la tienda. Se desactiva automáticamente cuando el stock llega a 0.', verbose_name='Disponible')),
                ('stock_ilimitado', models.BooleanField(default=False, help_text='Si está activo, el producto nunca se desactiva por falta de stock. Se activa automáticamente para tiendas de tipo COMIDA o SERVICIOS. Útil para productos bajo demanda como pizzas, hamburguesas, servicios, etc.', verbose_name='Stock ilimitado')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('imagen_qr_generado', models.ImageField(blank=True, help_text='Código QR generado automáticamente por la plataforma para gestión interna.', null=True, upload_to='codigos_qr/')),
                ('orden_display', models.PositiveIntegerField(default=0, help_text='Controla el orden en que aparece el producto en la tienda. Menor número = primero.', verbose_name='Orden de visualización')),
                ('loyverse_item_id', models.CharField(blank=True, help_text='ID del producto en Loyverse. Se completa al sincronizar con la integración.', max_length=100, null=True, verbose_name='ID item en Loyverse')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['orden_display', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='SubCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('orden_display', models.PositiveIntegerField(default=0, help_text='Controla el orden en que aparece la subcategoría. Menor número = primero.', verbose_name='Orden de visualización')),
            ],
            options={
                'verbose_name': 'Subcategoría',
                'verbose_name_plural': 'Subcategorías',
                'ordering': ['orden_display', 'nombre'],
            },
        ),
    ]
