# Generated by Django 5.2.4 on 2025-07-29 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        ('tiendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='tienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='tiendas.tienda'),
        ),
        migrations.AddField(
            model_name='producto',
            name='tienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='tiendas.tienda'),
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='productos.categoria'),
        ),
        migrations.AddField(
            model_name='producto',
            name='subcategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='productos.subcategoria'),
        ),
        migrations.AlterUniqueTogether(
            name='categoria',
            unique_together={('tienda', 'nombre')},
        ),
        migrations.AlterUniqueTogether(
            name='subcategoria',
            unique_together={('categoria', 'nombre')},
        ),
        migrations.AlterUniqueTogether(
            name='producto',
            unique_together={('tienda', 'sku')},
        ),
    ]
