# Generated by Django 5.2.4 on 2025-07-17 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
        ('tiendas', '0002_radioenvio_envio_gratis'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='sku',
            field=models.CharField(blank=True, help_text='Identificador único del producto dentro de la tienda.', max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='producto',
            unique_together={('tienda', 'sku')},
        ),
    ]
