# Generated by Django 5.2.4 on 2025-07-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_sku_alter_producto_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='codigo_barras_oficial',
            field=models.CharField(blank=True, help_text='Código de barras oficial (GTIN, EAN, UPC) del producto. Único a nivel global.', max_length=50, null=True, unique=True, verbose_name='Código de Barras GTIN/EAN/UPC'),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen_qr_generado',
            field=models.ImageField(blank=True, help_text='Código QR generado automáticamente por la plataforma para gestión interna.', null=True, upload_to='codigos_qr/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='sku',
            field=models.CharField(blank=True, help_text='Identificador único del producto dentro de la tienda (ej. SKU_ALF_CHOC_001).', max_length=50, null=True),
        ),
    ]
