# Generated by Django 5.2.4 on 2026-05-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['orden_display', 'nombre'], 'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['orden_display', 'nombre'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='subcategoria',
            options={'ordering': ['orden_display', 'nombre'], 'verbose_name': 'Subcategoría', 'verbose_name_plural': 'Subcategorías'},
        ),
        migrations.AddField(
            model_name='categoria',
            name='orden_display',
            field=models.PositiveIntegerField(default=0, help_text='Controla el orden en que aparece la categoría en la tienda. Menor número = primero.', verbose_name='Orden de visualización'),
        ),
        migrations.AddField(
            model_name='producto',
            name='loyverse_item_id',
            field=models.CharField(blank=True, help_text='ID del producto en Loyverse. Se completa al sincronizar con la integración.', max_length=100, null=True, verbose_name='ID item en Loyverse'),
        ),
        migrations.AddField(
            model_name='producto',
            name='orden_display',
            field=models.PositiveIntegerField(default=0, help_text='Controla el orden en que aparece el producto en la tienda. Menor número = primero.', verbose_name='Orden de visualización'),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_ilimitado',
            field=models.BooleanField(default=False, help_text='Si está activo, el producto nunca se desactiva por falta de stock. Se activa automáticamente para tiendas de tipo COMIDA o SERVICIOS. Útil para productos bajo demanda como pizzas, hamburguesas, servicios, etc.', verbose_name='Stock ilimitado'),
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='orden_display',
            field=models.PositiveIntegerField(default=0, help_text='Controla el orden en que aparece la subcategoría. Menor número = primero.', verbose_name='Orden de visualización'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo_barras_oficial',
            field=models.CharField(blank=True, help_text='Código de barras oficial del producto. Único a nivel global en la plataforma.', max_length=50, null=True, unique=True, verbose_name='Código de Barras GTIN/EAN/UPC'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='disponible',
            field=models.BooleanField(default=True, help_text='Controla si el producto se muestra en la tienda. Se desactiva automáticamente cuando el stock llega a 0.', verbose_name='Disponible'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_efectivo',
            field=models.DecimalField(decimal_places=0, help_text='Precio para pagos en efectivo o transferencia.', max_digits=10, verbose_name='Precio efectivo / transferencia'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_tarjeta',
            field=models.DecimalField(decimal_places=0, help_text='Precio con recargo por tarjeta. Si no hay recargo, ingresa el mismo valor que efectivo.', max_digits=10, verbose_name='Precio tarjeta débito/crédito'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='sku',
            field=models.CharField(blank=True, help_text='Identificador único del producto dentro de la tienda. Ej: SKU_ALF_CHOC_001.', max_length=50, null=True, verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='Cantidad disponible en inventario.', verbose_name='Stock'),
        ),
    ]
