# Generated by Django 5.2.4 on 2026-05-06 21:22

import plataforma_config.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(default='Mi Plataforma', help_text='Nombre que aparece en el encabezado, título del navegador y emails.', max_length=100, verbose_name='Nombre de la plataforma')),
                ('platform_description', models.CharField(blank=True, help_text='Descripción corta de la plataforma. Aparece en el SEO y página de inicio.', max_length=255, null=True, verbose_name='Descripción breve')),
                ('platform_logo', models.ImageField(blank=True, help_text='Logo principal de la plataforma. Recomendado: PNG transparente, 200x60px.', null=True, upload_to='platform_assets/', verbose_name='Logo de la plataforma')),
                ('favicon', models.ImageField(blank=True, help_text='Ícono del navegador. Recomendado: PNG o ICO, 32x32px.', null=True, upload_to='platform_assets/', verbose_name='Favicon')),
                ('primary_color_hex', models.CharField(blank=True, help_text='Color principal de botones y encabezados. Ej: #FF5733', max_length=7, null=True, validators=[plataforma_config.models.validar_color_hex], verbose_name='Color primario (HEX)')),
                ('secondary_color_hex', models.CharField(blank=True, help_text='Color de acento o secundario. Ej: #33C1FF', max_length=7, null=True, validators=[plataforma_config.models.validar_color_hex], verbose_name='Color secundario (HEX)')),
                ('store_card_layout', models.CharField(choices=[('grid', 'Cuadrícula'), ('list', 'Lista')], default='grid', help_text='Define cómo se muestran las tiendas en la página principal.', max_length=10, verbose_name='Diseño de tarjetas de tienda')),
                ('terms_and_conditions', models.TextField(blank=True, help_text='Texto completo de los términos y condiciones de uso de la plataforma.', null=True, verbose_name='Términos y Condiciones')),
                ('privacy_policy', models.TextField(blank=True, help_text='Texto completo de la política de privacidad.', null=True, verbose_name='Política de Privacidad')),
                ('soporte_email', models.EmailField(blank=True, help_text='Email de contacto para soporte de la plataforma.', max_length=254, null=True, verbose_name='Email de soporte')),
                ('soporte_whatsapp', models.CharField(blank=True, help_text='Número de WhatsApp de soporte en formato internacional. Ej: +56912345678', max_length=15, null=True, verbose_name='WhatsApp de soporte')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Configuración de Plataforma',
                'verbose_name_plural': 'Configuración de Plataforma',
            },
        ),
    ]
