# Generated by Django 5.2.4 on 2025-07-29 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_logo', models.ImageField(blank=True, null=True, upload_to='platform_assets/', verbose_name='Logo de la Plataforma')),
                ('primary_color_hex', models.CharField(blank=True, max_length=7, null=True, verbose_name='Color Primario (HEX)')),
                ('secondary_color_hex', models.CharField(blank=True, max_length=7, null=True, verbose_name='Color Secundario (HEX)')),
                ('terms_and_conditions', models.TextField(blank=True, null=True, verbose_name='Términos y Condiciones')),
                ('privacy_policy', models.TextField(blank=True, null=True, verbose_name='Política de Privacidad')),
                ('store_card_layout', models.CharField(choices=[('grid', 'Cuadrícula'), ('list', 'Lista')], default='grid', max_length=10, verbose_name='Diseño de Tarjetas de Tienda')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Plataforma',
                'verbose_name_plural': 'Configuración de Plataforma',
            },
        ),
    ]
