# Generated by Django 5.2.4 on 2026-05-06 15:34

import plataforma_config.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma_config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsetting',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Ícono del navegador. Recomendado: PNG o ICO, 32x32px.', null=True, upload_to='platform_assets/', verbose_name='Favicon'),
        ),
        migrations.AddField(
            model_name='platformsetting',
            name='platform_description',
            field=models.CharField(blank=True, help_text='Descripción corta de la plataforma. Aparece en el SEO y página de inicio.', max_length=255, null=True, verbose_name='Descripción breve'),
        ),
        migrations.AddField(
            model_name='platformsetting',
            name='platform_name',
            field=models.CharField(default='Mi Plataforma', help_text='Nombre que aparece en el encabezado, título del navegador y emails.', max_length=100, verbose_name='Nombre de la plataforma'),
        ),
        migrations.AddField(
            model_name='platformsetting',
            name='soporte_email',
            field=models.EmailField(blank=True, help_text='Email de contacto para soporte de la plataforma.', max_length=254, null=True, verbose_name='Email de soporte'),
        ),
        migrations.AddField(
            model_name='platformsetting',
            name='soporte_whatsapp',
            field=models.CharField(blank=True, help_text='Número de WhatsApp de soporte en formato internacional. Ej: +56912345678', max_length=15, null=True, verbose_name='WhatsApp de soporte'),
        ),
        migrations.AlterField(
            model_name='platformsetting',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
        migrations.AlterField(
            model_name='platformsetting',
            name='platform_logo',
            field=models.ImageField(blank=True, help_text='Logo principal de la plataforma. Recomendado: PNG transparente, 200x60px.', null=True, upload_to='platform_assets/', verbose_name='Logo de la plataforma'),
        ),
        migrations.AlterField(
            model_name='platformsetting',
            name='primary_color_hex',
            field=models.CharField(blank=True, help_text='Color principal de botones y encabezados. Ej: #FF5733', max_length=7, null=True, validators=[plataforma_config.models.validar_color_hex], verbose_name='Color primario (HEX)'),
        ),
        migrations.AlterField(
            model_name='platformsetting',
            name='privacy_policy',
            field=models.TextField(blank=True, help_text='Texto completo de la política de privacidad.', null=True, verbose_name='Política de Privacidad'),
        ),
        migrations.AlterField(
            model_name='platformsetting',
            name='secondary_color_hex',
            field=models.CharField(blank=True, help_text='Color de acento o secundario. Ej: #33C1FF', max_length=7, null=True, validators=[plataforma_config.models.validar_color_hex], verbose_name='Color secundario (HEX)'),
        ),
        migrations.AlterField(
            model_name='platformsetting',
            name='store_card_layout',
            field=models.CharField(choices=[('grid', 'Cuadrícula'), ('list', 'Lista')], default='grid', help_text='Define cómo se muestran las tiendas en la página principal.', max_length=10, verbose_name='Diseño de tarjetas de tienda'),
        ),
        migrations.AlterField(
            model_name='platformsetting',
            name='terms_and_conditions',
            field=models.TextField(blank=True, help_text='Texto completo de los términos y condiciones de uso de la plataforma.', null=True, verbose_name='Términos y Condiciones'),
        ),
    ]
