# Generated by Django 5.2.4 on 2026-05-09 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma_config', '0003_initial_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriatienda',
            name='tipo_negocio',
            field=models.CharField(choices=[('COMIDA', 'Comida y Bebidas'), ('RETAIL', 'Tienda / Retail'), ('SERVICIOS', 'Servicios'), ('OTRO', 'Otro')], default='COMIDA', help_text='Filtra las tiendas de este tipo al seleccionar la categoría.', max_length=20, verbose_name='Tipo de negocio'),
        ),
    ]
