# Generated by Django 5.2.4 on 2026-05-17 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma_config', '0004_alter_categoriatienda_tipo_negocio'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsetting',
            name='hero_banner',
            field=models.ImageField(blank=True, help_text='Imagen hero de la página de inicio. Recomendado: 1200x400px.', null=True, upload_to='platform_assets/', verbose_name='Banner de la página principal'),
        ),
    ]
