# Generated by Django 5.2.4 on 2025-07-04 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('direccion', models.CharField(max_length=255)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('horario_atencion', models.CharField(blank=True, max_length=255, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos_tiendas/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiendas', to='usuarios.perfilvendedor')),
            ],
            options={
                'verbose_name_plural': 'Tiendas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='RadioEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distancia_max_km', models.DecimalField(decimal_places=1, max_digits=4)),
                ('costo_envio', models.PositiveIntegerField()),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='radios_envio', to='tiendas.tienda')),
            ],
            options={
                'verbose_name_plural': 'Radios de Envío',
                'ordering': ['distancia_max_km'],
                'unique_together': {('tienda', 'distancia_max_km')},
            },
        ),
    ]
