# Generated by Django 5.2.4 on 2025-07-11 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='radioenvio',
            name='envio_gratis',
            field=models.BooleanField(default=False),
        ),
    ]
