# Generated by Django 5.2.4 on 2025-07-29 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tiendas', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='propietario_perfil',
            field=models.ForeignKey(help_text='El perfil del vendedor asociado a esta tienda.', on_delete=django.db.models.deletion.CASCADE, related_name='tiendas_gestionadas', to='usuarios.sellerprofile', verbose_name='Perfil del Vendedor Propietario'),
        ),
        migrations.AddField(
            model_name='radioenvio',
            name='tienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='radios_envio', to='tiendas.tienda'),
        ),
        migrations.AlterUniqueTogether(
            name='radioenvio',
            unique_together={('tienda', 'distancia_max_km')},
        ),
    ]
