# Generated by Django 5.2.4 on 2026-05-06 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendas', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='radioenvio',
            options={'ordering': ['distancia_max_km'], 'verbose_name': 'Radio de Envío', 'verbose_name_plural': 'Radios de Envío'},
        ),
        migrations.AddField(
            model_name='tienda',
            name='acepta_efectivo',
            field=models.BooleanField(default=True, help_text='El cliente paga en efectivo al momento de la entrega o retiro.', verbose_name='Acepta efectivo'),
        ),
        migrations.AddField(
            model_name='tienda',
            name='acepta_link_pago',
            field=models.BooleanField(default=False, help_text='El emprendedor comparte un link de pago (Flow, Khipu, MercadoPago, etc.).', verbose_name='Acepta link de pago'),
        ),
        migrations.AddField(
            model_name='tienda',
            name='acepta_transferencia',
            field=models.BooleanField(default=False, help_text='El cliente realiza una transferencia bancaria.', verbose_name='Acepta transferencia bancaria'),
        ),
        migrations.AddField(
            model_name='tienda',
            name='banco',
            field=models.CharField(blank=True, choices=[('Banco de Chile', 'Banco de Chile'), ('Banco Estado', 'Banco Estado'), ('Banco BCI', 'Banco BCI'), ('Banco Santander', 'Banco Santander'), ('Banco Scotiabank', 'Banco Scotiabank'), ('Banco Itaú', 'Banco Itaú'), ('Banco Falabella', 'Banco Falabella'), ('Banco Ripley', 'Banco Ripley'), ('Banco Security', 'Banco Security'), ('Banco BICE', 'Banco BICE'), ('Coopeuch', 'Coopeuch'), ('Otro', 'Otro')], max_length=50, null=True, verbose_name='Banco'),
        ),
        migrations.AddField(
            model_name='tienda',
            name='email_transferencia',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email para transferencia'),
        ),
        migrations.AddField(
            model_name='tienda',
            name='instrucciones_link_pago',
            field=models.CharField(blank=True, help_text="Ej: 'Paga por Flow e indica tu número de pedido'.", max_length=255, null=True, verbose_name='Instrucciones del link de pago'),
        ),
        migrations.AddField(
            model_name='tienda',
            name='link_pago_url',
            field=models.URLField(blank=True, help_text='Link de pago (Flow, Khipu, MercadoPago, etc.).', null=True, verbose_name='Link de pago'),
        ),
        migrations.AddField(
            model_name='tienda',
            name='loyverse_activo',
            field=models.BooleanField(default=False, help_text='Activa la sincronización automática con Loyverse al confirmar pedidos. Requiere token y store ID configurados.', verbose_name='Integración con Loyverse activa'),
        ),
        migrations.AddField(
            model_name='tienda',
            name='loyverse_store_id',
            field=models.CharField(blank=True, help_text='ID de la tienda en Loyverse. Necesario para crear receipts asociados a la tienda correcta.', max_length=100, null=True, verbose_name='ID de tienda en Loyverse'),
        ),
        migrations.AddField(
            model_name='tienda',
            name='loyverse_token',
            field=models.CharField(blank=True, help_text='Token de acceso a la API de Loyverse. Se obtiene en: Loyverse Back Office → Configuración → API. ⚠️ Mantén este token seguro, no lo compartas.', max_length=255, null=True, verbose_name='Token API de Loyverse'),
        ),
        migrations.AddField(
            model_name='tienda',
            name='modo_asignacion_default',
            field=models.CharField(choices=[('LIBRE', 'Libre — cualquier repartidor puede tomarlo'), ('CERRADO', 'Cerrado — el emprendedor lo asigna manualmente')], default='LIBRE', help_text='Define cómo se asignan los pedidos a los repartidores por defecto. LIBRE: cualquier repartidor activo puede tomarlo. CERRADO: el emprendedor lo asigna manualmente.', max_length=10, verbose_name='Modo de asignación por defecto'),
        ),
        migrations.AddField(
            model_name='tienda',
            name='numero_cuenta',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Número de cuenta'),
        ),
        migrations.AddField(
            model_name='tienda',
            name='rut_titular',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='RUT del titular'),
        ),
        migrations.AddField(
            model_name='tienda',
            name='tipo_cuenta',
            field=models.CharField(blank=True, choices=[('Cuenta Corriente', 'Cuenta Corriente'), ('Cuenta Vista', 'Cuenta Vista'), ('Cuenta RUT', 'Cuenta RUT'), ('Cuenta de Ahorro', 'Cuenta de Ahorro')], max_length=30, null=True, verbose_name='Tipo de cuenta'),
        ),
        migrations.AddField(
            model_name='tienda',
            name='tipo_negocio',
            field=models.CharField(choices=[('COMIDA', 'Comida y Bebidas'), ('RETAIL', 'Tienda / Retail'), ('SERVICIOS', 'Servicios'), ('OTRO', 'Otro')], default='COMIDA', help_text='Define el tipo de negocio. COMIDA: productos bajo demanda, sin control de stock por defecto. RETAIL: productos con stock real, se desactivan al llegar a 0.', max_length=20, verbose_name='Tipo de negocio'),
        ),
        migrations.AddField(
            model_name='tienda',
            name='titular_cuenta',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Titular de la cuenta'),
        ),
        migrations.AlterField(
            model_name='radioenvio',
            name='costo_envio',
            field=models.DecimalField(decimal_places=0, default=0, help_text="Costo en pesos chilenos. Se ignora si 'envío gratis' está activo.", max_digits=10, verbose_name='Costo de envío ($)'),
        ),
        migrations.AlterField(
            model_name='radioenvio',
            name='distancia_max_km',
            field=models.DecimalField(decimal_places=1, help_text='Límite superior de este radio. Ej: 1, 3, 5. Cubre desde 0 hasta este valor.', max_digits=4, verbose_name='Distancia máxima (km)'),
        ),
        migrations.AlterField(
            model_name='radioenvio',
            name='envio_gratis',
            field=models.BooleanField(default=False, help_text='Si está activo, el envío es gratuito para este radio.', verbose_name='Envío gratis'),
        ),
        migrations.CreateModel(
            name='CuadranteEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text="Nombre descriptivo. Ej: 'Las Acequias', 'Sector Norte', 'Villa El Bosque'.", max_length=100, verbose_name='Nombre del sector')),
                ('descripcion', models.CharField(blank=True, help_text="Nota interna. Ej: 'Cerro sin pavimento, difícil acceso en invierno'.", max_length=255, null=True, verbose_name='Descripción interna')),
                ('poligono', models.JSONField(help_text="Lista de coordenadas que definen el área del sector. Formato: [{'lat': -37.79, 'lng': -72.70}, ...]. Se genera automáticamente al dibujar en el mapa.", verbose_name='Coordenadas del polígono')),
                ('costo_envio', models.DecimalField(decimal_places=0, default=0, help_text="Costo en pesos chilenos. Se ignora si 'envío gratis' está activo.", max_digits=10, verbose_name='Costo de envío ($)')),
                ('envio_gratis', models.BooleanField(default=False, help_text='Si está activo, el envío es gratuito para este sector.', verbose_name='Envío gratis')),
                ('activo', models.BooleanField(default=True, help_text='Desactiva el cuadrante sin eliminarlo. Útil para temporadas o condiciones especiales.', verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuadrantes', to='tiendas.tienda')),
            ],
            options={
                'verbose_name': 'Cuadrante de Envío',
                'verbose_name_plural': 'Cuadrantes de Envío',
                'ordering': ['nombre'],
            },
        ),
    ]
