# Generated by Django 5.2.4 on 2026-05-13 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='abre_domingo',
            field=models.BooleanField(default=False, verbose_name='Domingo'),
        ),
        migrations.AddField(
            model_name='tienda',
            name='abre_jueves',
            field=models.BooleanField(default=True, verbose_name='Jueves'),
        ),
        migrations.AddField(
            model_name='tienda',
            name='abre_lunes',
            field=models.BooleanField(default=True, verbose_name='Lunes'),
        ),
        migrations.AddField(
            model_name='tienda',
            name='abre_martes',
            field=models.BooleanField(default=True, verbose_name='Martes'),
        ),
        migrations.AddField(
            model_name='tienda',
            name='abre_miercoles',
            field=models.BooleanField(default=True, verbose_name='Miércoles'),
        ),
        migrations.AddField(
            model_name='tienda',
            name='abre_sabado',
            field=models.BooleanField(default=False, verbose_name='Sábado'),
        ),
        migrations.AddField(
            model_name='tienda',
            name='abre_viernes',
            field=models.BooleanField(default=True, verbose_name='Viernes'),
        ),
        migrations.AddField(
            model_name='tienda',
            name='acepta_pedidos_programados',
            field=models.BooleanField(default=False, help_text='Permite que los clientes programen pedidos fuera del horario de atención.', verbose_name='Acepta pedidos programados'),
        ),
        migrations.AddField(
            model_name='tienda',
            name='hora_apertura',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de apertura'),
        ),
        migrations.AddField(
            model_name='tienda',
            name='hora_cierre',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de cierre'),
        ),
    ]
