# Generated by Django 5.2.4 on 2026-05-15 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendas', '0003_tienda_abre_domingo_tienda_abre_jueves_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='banner',
            field=models.ImageField(blank=True, help_text='Imagen de portada. Recomendado: 1200x400px', null=True, upload_to='banners_tiendas/'),
        ),
    ]
